---
# simple_ssh_config/tasks/main.yml

- name: 'Set primary group to users on SUSE/openSUSE'
  ansible.builtin.set_fact:
    primary_group_name: 'users'
  when:
    - '
      ansible_os_family == "Suse"
      or ansible_os_family == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Tumbleweed"
      '

- name: 'Create the directory ~/.ssh/'
  ansible.builtin.file:
    path: "{{ item.home }}/.ssh/"
    state: 'directory'
    owner: "{{ item.name }}"
    group: "{{ primary_group_name | default(item.name) }}"
    mode: '0700'
  with_items: "{{ list_of_users }}"

- name: 'Create a ~/.ssh/config'
  ansible.builtin.template:
    src: 'ssh_config.j2'
    dest: "{{ item.home }}/.ssh/config"
    owner: "{{ item.name }}"
    group: "{{ primary_group_name | default(item.name) }}"
    mode: '0600'
  with_items: "{{ list_of_users }}"
